export const SUPPORTED_UNIVERSITIES = [
  'Columbia University in the City of New York',
  'Duke University',
  'Georgia Institute of Technology',
  'Harvard University',
  'Massachusetts Institute of Technology',
  'New York University',
  'Northwestern University',
  'Princeton University',
  'Purdue University',
  'Rice University',
  'Stanford University',
  'The University of Texas at Austin',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of Florida',
  'University of Illinois Urbana-Champaign',
  'University of Michigan – Ann Arbor',
  'University of Pennsylvania',
  'University of Southern California',
  'University of Virginia',
  'University of Washington',
  'Washington State University',
  'Yale University',
];
