// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wweddjwjzuscorqajfvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZWRkandqenVzY29ycWFqZnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2ODYxNTEsImV4cCI6MjA5MTI2MjE1MX0.jKJUdnC9O1J08kVbqqXZ_VYeP63RKw5smSP6-N3w1X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});